// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CoachDto = null;

export type CourtDto = {
    id?: number;
    name: string;
    surface: 'CLAY' | 'HARD' | 'WIMBLEDON';
    indoor: boolean;
    lighting: boolean;
    venue: VenueDto;
};

export type GroupDto = {
    id?: number;
    name: string;
    level: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'PRO';
    coach?: CoachDto;
    capacity: number;
    season: SeasonDto;
};

export type SeasonDto = {
    id?: number;
    name: string;
    dateFrom: string;
    dateUntil: string;
};

export type TrainingSlotDto = {
    id?: number;
    group: GroupDto;
    court: CourtDto;
    startAt: string;
    endAt: string;
    capacity?: number;
    status: 'OPEN' | 'CANCELED';
    price?: string;
    currency: string;
    courtBlockingId?: number;
};

export type UserDto = {
    id?: number;
    email: string;
    telephoneNumber?: string;
    fullName: string;
    roles: Array<'ADMIN' | 'COACH' | 'PARENT' | 'PLAYER'>;
    createdAt?: string;
};

export type VenueDto = {
    id?: number;
    name: string;
    address: string;
    phoneNumber: string;
};

export type WeatherNotesDto = {
    id?: number;
    trainingSlot: TrainingSlotDto;
    weatherCondition?: 'RAIN' | 'WIND' | 'HEAT' | 'OK';
    note?: string;
};

export type PackageDto = {
    id?: number;
    player: PlayerDto;
    name: string;
    availableSlots?: number;
    validFrom: string;
    validTo: string;
    generatedAt?: string;
    path?: string;
    pricingRuleId: number;
};

export type PlayerDto = {
    id?: number;
    fullName: string;
    birthDate: string;
    handedness: 'LEFT' | 'RIGHT';
    parent: UserDto;
    pricingType?: 'PER_SLOT' | 'MONTHLY' | 'PACKAGE';
    note?: string;
    packagee?: unknown;
};

export type PricingRuleDto = {
    id?: number;
    name: string;
    pricingType: 'PER_SLOT' | 'MONTHLY' | 'PACKAGE';
    amountCents: number;
    currency: string;
    conditions?: {
        [key: string]: unknown;
    };
    packagee?: Array<PackageDto>;
};

export type InvoiceSummaryDto = {
    id?: number;
    player: PlayerDto;
    month: 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER';
    totalCentsAmount?: number;
    rule?: PricingRuleDto;
    currency: string;
    generatedAt?: string;
    path?: string;
};

export type EnrollmentDto = {
    id?: number;
    player: PlayerDto;
    group: GroupDto;
    state?: 'ACTIVE' | 'WAITLIST' | 'CANCELLED';
    createdAt?: string;
};

export type CourtBlockingDto = {
    id?: number;
    court: CourtDto;
    blockedFrom: string;
    blockedTo: string;
    reason: string;
    range?: RangeLocalDateTime;
};

export type RangeLocalDateTime = {
    empty?: boolean;
    boundedOpen?: boolean;
    lowerBoundClosed?: boolean;
    upperBoundClosed?: boolean;
    bounded?: boolean;
};

export type BookingDto = {
    id?: number;
    trainingSlot: TrainingSlotDto;
    player: PlayerDto;
    bookingStatus?: 'CONFIRMED' | 'CANCELED' | 'NO_SHOW' | 'WAITLIST';
    bookedAt?: string;
};

export type AttendanceDto = {
    id?: number;
    booking: BookingDto;
    present?: boolean;
    note?: string;
    createdAt?: string;
};

export type AuthRequestDto = {
    username?: string;
    password?: string;
};

export type LoginResponseDto = {
    token?: string;
    expiresIn?: number;
};

export type RegistrationRequestDto = {
    email: string;
    password: string;
    telephoneNumber: string;
    fullName: string;
};

export type CompanyInfoDto = {
    companyName?: string;
    address?: string;
    businessId?: string;
    taxNumber?: string;
    email?: string;
    telNumber?: string;
    bankAccount?: string;
    bankAccountInternationalFormat?: string;
};

export type GrantedAuthority = {
    authority?: string;
};

export type User = {
    password?: string;
    username?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
    enabled?: boolean;
};

export type UserFilter = {
    email?: string;
    telephoneNumber?: string;
    fullName?: string;
    roles?: Array<'ADMIN' | 'COACH' | 'PARENT' | 'PLAYER'>;
    createdBefore?: string;
    createdAfter?: string;
    isCoach?: boolean;
};

export type PlayerFilter = {
    name?: string;
    birthAfter?: string;
    birthBefore?: string;
    handedness?: 'LEFT' | 'RIGHT';
    parentId?: number;
    pricingType?: 'PER_SLOT' | 'MONTHLY' | 'PACKAGE';
    note?: string;
};

export type PackageFilter = {
    playerId?: number;
    name?: string;
    validAfter?: string;
    validBefore?: string;
    hasAvailableSlots?: boolean;
    availableSlotsMin?: number;
};

export type InvoiceSummaryFilter = {
    playerId?: number;
    month?: 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER';
    amountOfCentsBiggerThan?: number;
    amountOfCentsLessThan?: number;
    createdAfter?: string;
    createdBefore?: string;
};

export type GroupFilter = {
    coachId?: number;
    seasonId?: number;
    name?: string;
    capacityMin?: number;
    capacityMax?: number;
};

export type EnrollmentFilter = {
    playerId?: number;
    groupId?: number;
    state?: 'ACTIVE' | 'WAITLIST' | 'CANCELLED';
    createdAfter?: string;
    createdBefore?: string;
};

export type CourtFilter = {
    venueId?: number;
    name?: string;
    surface?: 'CLAY' | 'HARD' | 'WIMBLEDON';
    indoor?: boolean;
    lighting?: boolean;
};

export type CourtBlockingFilter = {
    courtId?: number;
    moreThanHour?: boolean;
    reason?: string;
};

export type BookingFilter = {
    trainingSlotId?: number;
    playerId?: number;
    bookingStatus?: 'CONFIRMED' | 'CANCELED' | 'NO_SHOW' | 'WAITLIST';
    createdAfter?: string;
    createdBefore?: string;
};

export type AttendanceFilter = {
    present?: boolean;
    createdAfter?: string;
    createdBefore?: string;
    note?: string;
};

export type DeleteWeatherNoteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/weather-notes/{id}';
};

export type DeleteWeatherNoteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteWeatherNoteResponse = DeleteWeatherNoteResponses[keyof DeleteWeatherNoteResponses];

export type GetWeatherNoteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/weather-notes/{id}';
};

export type GetWeatherNoteResponses = {
    /**
     * OK
     */
    200: WeatherNotesDto;
};

export type GetWeatherNoteResponse = GetWeatherNoteResponses[keyof GetWeatherNoteResponses];

export type EditWeatherNoteData = {
    body: WeatherNotesDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/weather-notes/{id}';
};

export type EditWeatherNoteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditWeatherNoteResponse = EditWeatherNoteResponses[keyof EditWeatherNoteResponses];

export type DeleteVenueData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/venue/{id}';
};

export type DeleteVenueResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteVenueResponse = DeleteVenueResponses[keyof DeleteVenueResponses];

export type GetVenueData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/venue/{id}';
};

export type GetVenueResponses = {
    /**
     * OK
     */
    200: VenueDto;
};

export type GetVenueResponse = GetVenueResponses[keyof GetVenueResponses];

export type EditVenueData = {
    body: VenueDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/venue/{id}';
};

export type EditVenueResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditVenueResponse = EditVenueResponses[keyof EditVenueResponses];

export type DeleteTrainingSlotData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/training-slot/{id}';
};

export type DeleteTrainingSlotResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTrainingSlotResponse = DeleteTrainingSlotResponses[keyof DeleteTrainingSlotResponses];

export type GetTrainingSlotData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/training-slot/{id}';
};

export type GetTrainingSlotResponses = {
    /**
     * OK
     */
    200: TrainingSlotDto;
};

export type GetTrainingSlotResponse = GetTrainingSlotResponses[keyof GetTrainingSlotResponses];

export type EditTrainingSlotData = {
    body: TrainingSlotDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/training-slot/{id}';
};

export type EditTrainingSlotResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditTrainingSlotResponse = EditTrainingSlotResponses[keyof EditTrainingSlotResponses];

export type DeleteSeasonData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/season/{id}';
};

export type DeleteSeasonResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSeasonResponse = DeleteSeasonResponses[keyof DeleteSeasonResponses];

export type GetSeasonData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/season/{id}';
};

export type GetSeasonResponses = {
    /**
     * OK
     */
    200: SeasonDto;
};

export type GetSeasonResponse = GetSeasonResponses[keyof GetSeasonResponses];

export type EditSeasonData = {
    body: SeasonDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/season/{id}';
};

export type EditSeasonResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditSeasonResponse = EditSeasonResponses[keyof EditSeasonResponses];

export type DeleteRuleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/pricing-rules/{id}';
};

export type DeleteRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRuleResponse = DeleteRuleResponses[keyof DeleteRuleResponses];

export type GetRuleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/pricing-rules/{id}';
};

export type GetRuleResponses = {
    /**
     * OK
     */
    200: PricingRuleDto;
};

export type GetRuleResponse = GetRuleResponses[keyof GetRuleResponses];

export type UpdateRuleData = {
    body: PricingRuleDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/pricing-rules/{id}';
};

export type UpdateRuleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateRuleResponse = UpdateRuleResponses[keyof UpdateRuleResponses];

export type DeletePlayerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/player/{id}';
};

export type DeletePlayerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePlayerResponse = DeletePlayerResponses[keyof DeletePlayerResponses];

export type GetPlayerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/player/{id}';
};

export type GetPlayerResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPlayerResponse = GetPlayerResponses[keyof GetPlayerResponses];

export type EditPlayerData = {
    body: PlayerDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/player/{id}';
};

export type EditPlayerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditPlayerResponse = EditPlayerResponses[keyof EditPlayerResponses];

export type DeletePackageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/package/{id}';
};

export type DeletePackageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePackageResponse = DeletePackageResponses[keyof DeletePackageResponses];

export type ShowPackageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/package/{id}';
};

export type ShowPackageResponses = {
    /**
     * OK
     */
    200: PackageDto;
};

export type ShowPackageResponse = ShowPackageResponses[keyof ShowPackageResponses];

export type EditPackageData = {
    body: PackageDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/package/{id}';
};

export type EditPackageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditPackageResponse = EditPackageResponses[keyof EditPackageResponses];

export type DeleteSummaryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/invoice-summary/{id}';
};

export type DeleteSummaryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSummaryResponse = DeleteSummaryResponses[keyof DeleteSummaryResponses];

export type GetSummaryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/invoice-summary/{id}';
};

export type GetSummaryResponses = {
    /**
     * OK
     */
    200: InvoiceSummaryDto;
};

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses];

export type EditSummaryData = {
    body: InvoiceSummaryDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/invoice-summary/{id}';
};

export type EditSummaryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditSummaryResponse = EditSummaryResponses[keyof EditSummaryResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/group/{id}';
};

export type DeleteGroupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/group/{id}';
};

export type GetGroupResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type EditGroupData = {
    body: GroupDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/group/{id}';
};

export type EditGroupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditGroupResponse = EditGroupResponses[keyof EditGroupResponses];

export type DeleteEnrollmentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/enrollment/{id}';
};

export type DeleteEnrollmentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEnrollmentResponse = DeleteEnrollmentResponses[keyof DeleteEnrollmentResponses];

export type GetEnrollmentData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/enrollment/{id}';
};

export type GetEnrollmentResponses = {
    /**
     * OK
     */
    200: EnrollmentDto;
};

export type GetEnrollmentResponse = GetEnrollmentResponses[keyof GetEnrollmentResponses];

export type EditEnrollmentData = {
    body: EnrollmentDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/enrollment/{id}';
};

export type EditEnrollmentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditEnrollmentResponse = EditEnrollmentResponses[keyof EditEnrollmentResponses];

export type DeleteCourtData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court/{id}';
};

export type DeleteCourtResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCourtResponse = DeleteCourtResponses[keyof DeleteCourtResponses];

export type ShowCourtData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court/{id}';
};

export type ShowCourtResponses = {
    /**
     * OK
     */
    200: CourtDto;
};

export type ShowCourtResponse = ShowCourtResponses[keyof ShowCourtResponses];

export type EditCourtData = {
    body: CourtDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court/{id}';
};

export type EditCourtResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditCourtResponse = EditCourtResponses[keyof EditCourtResponses];

export type DeleteBlockingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court-block/{id}';
};

export type DeleteBlockingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBlockingResponse = DeleteBlockingResponses[keyof DeleteBlockingResponses];

export type GetBlockingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court-block/{id}';
};

export type GetBlockingResponses = {
    /**
     * OK
     */
    200: CourtBlockingDto;
};

export type GetBlockingResponse = GetBlockingResponses[keyof GetBlockingResponses];

export type EditBlockingData = {
    body: CourtBlockingDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/court-block/{id}';
};

export type EditBlockingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditBlockingResponse = EditBlockingResponses[keyof EditBlockingResponses];

export type DeleteCoachData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/coach/{id}';
};

export type DeleteCoachResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCoachResponse = DeleteCoachResponses[keyof DeleteCoachResponses];

export type GetCoachData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/coach/{id}';
};

export type GetCoachResponses = {
    /**
     * OK
     */
    200: CoachDto;
};

export type GetCoachResponse = GetCoachResponses[keyof GetCoachResponses];

export type EditCoachData = {
    body: CoachDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/coach/{id}';
};

export type EditCoachResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditCoachResponse = EditCoachResponses[keyof EditCoachResponses];

export type DeleteBookingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/booking/{id}';
};

export type DeleteBookingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBookingResponse = DeleteBookingResponses[keyof DeleteBookingResponses];

export type GetBookingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/booking/{id}';
};

export type GetBookingResponses = {
    /**
     * OK
     */
    200: BookingDto;
};

export type GetBookingResponse = GetBookingResponses[keyof GetBookingResponses];

export type EditBookingData = {
    body: BookingDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/booking/{id}';
};

export type EditBookingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditBookingResponse = EditBookingResponses[keyof EditBookingResponses];

export type EditBookingAsAdminData = {
    body: BookingDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/booking/admin/{id}';
};

export type EditBookingAsAdminResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditBookingAsAdminResponse = EditBookingAsAdminResponses[keyof EditBookingAsAdminResponses];

export type DeleteAttendanceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/attendance/{id}';
};

export type DeleteAttendanceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAttendanceResponse = DeleteAttendanceResponses[keyof DeleteAttendanceResponses];

export type GetAttendanceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/attendance/{id}';
};

export type GetAttendanceResponses = {
    /**
     * OK
     */
    200: AttendanceDto;
};

export type GetAttendanceResponse = GetAttendanceResponses[keyof GetAttendanceResponses];

export type EditAttendanceData = {
    body: AttendanceDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/attendance/{id}';
};

export type EditAttendanceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EditAttendanceResponse = EditAttendanceResponses[keyof EditAttendanceResponses];

export type AuthenticateAndGetTokenData = {
    body: AuthRequestDto;
    path?: never;
    query?: never;
    url: '/auth/generateToken';
};

export type AuthenticateAndGetTokenResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type AuthenticateAndGetTokenResponse = AuthenticateAndGetTokenResponses[keyof AuthenticateAndGetTokenResponses];

export type CreateUserData = {
    body: RegistrationRequestDto;
    path?: never;
    query?: never;
    url: '/auth/addNewUser';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetAllWeatherNotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/weather-notes';
};

export type GetAllWeatherNotesResponses = {
    /**
     * OK
     */
    200: Array<WeatherNotesDto>;
};

export type GetAllWeatherNotesResponse = GetAllWeatherNotesResponses[keyof GetAllWeatherNotesResponses];

export type CreateWeatherNoteData = {
    body: WeatherNotesDto;
    path?: never;
    query?: never;
    url: '/api/weather-notes';
};

export type CreateWeatherNoteResponses = {
    /**
     * OK
     */
    200: WeatherNotesDto;
};

export type CreateWeatherNoteResponse = CreateWeatherNoteResponses[keyof CreateWeatherNoteResponses];

export type GetAllVenuesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venue';
};

export type GetAllVenuesResponses = {
    /**
     * OK
     */
    200: Array<VenueDto>;
};

export type GetAllVenuesResponse = GetAllVenuesResponses[keyof GetAllVenuesResponses];

export type CreateVenueData = {
    body: VenueDto;
    path?: never;
    query?: never;
    url: '/api/venue';
};

export type CreateVenueResponses = {
    /**
     * OK
     */
    200: VenueDto;
};

export type CreateVenueResponse = CreateVenueResponses[keyof CreateVenueResponses];

export type GetAllTrainingSlotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/training-slot';
};

export type GetAllTrainingSlotsResponses = {
    /**
     * OK
     */
    200: Array<TrainingSlotDto>;
};

export type GetAllTrainingSlotsResponse = GetAllTrainingSlotsResponses[keyof GetAllTrainingSlotsResponses];

export type CreateTrainingSlotData = {
    body: TrainingSlotDto;
    path?: never;
    query?: never;
    url: '/api/training-slot';
};

export type CreateTrainingSlotResponses = {
    /**
     * Created
     */
    201: TrainingSlotDto;
};

export type CreateTrainingSlotResponse = CreateTrainingSlotResponses[keyof CreateTrainingSlotResponses];

export type GetAllSeasonsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/season';
};

export type GetAllSeasonsResponses = {
    /**
     * OK
     */
    200: Array<SeasonDto>;
};

export type GetAllSeasonsResponse = GetAllSeasonsResponses[keyof GetAllSeasonsResponses];

export type CreateSeasonData = {
    body: SeasonDto;
    path?: never;
    query?: never;
    url: '/api/season';
};

export type CreateSeasonResponses = {
    /**
     * OK
     */
    200: SeasonDto;
};

export type CreateSeasonResponse = CreateSeasonResponses[keyof CreateSeasonResponses];

export type GetAllRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules';
};

export type GetAllRulesResponses = {
    /**
     * OK
     */
    200: Array<PricingRuleDto>;
};

export type GetAllRulesResponse = GetAllRulesResponses[keyof GetAllRulesResponses];

export type CreateRuleData = {
    body: PricingRuleDto;
    path?: never;
    query?: never;
    url: '/api/pricing-rules';
};

export type CreateRuleResponses = {
    /**
     * OK
     */
    200: PricingRuleDto;
};

export type CreateRuleResponse = CreateRuleResponses[keyof CreateRuleResponses];

export type GetAllPlayersData = {
    body?: never;
    path?: never;
    query: {
        playerFilter: PlayerFilter;
    };
    url: '/api/player';
};

export type GetAllPlayersResponses = {
    /**
     * OK
     */
    200: Array<PlayerDto>;
};

export type GetAllPlayersResponse = GetAllPlayersResponses[keyof GetAllPlayersResponses];

export type CreatePlayerData = {
    body: PlayerDto;
    path?: never;
    query?: never;
    url: '/api/player';
};

export type CreatePlayerResponses = {
    /**
     * OK
     */
    200: PlayerDto;
};

export type CreatePlayerResponse = CreatePlayerResponses[keyof CreatePlayerResponses];

export type CreatePackageData = {
    body: PackageDto;
    path?: never;
    query?: never;
    url: '/api/package/create';
};

export type CreatePackageResponses = {
    /**
     * Created
     */
    201: PackageDto;
};

export type CreatePackageResponse = CreatePackageResponses[keyof CreatePackageResponses];

export type GetAllSummariesData = {
    body?: never;
    path?: never;
    query: {
        invoiceSummaryFilter: InvoiceSummaryFilter;
    };
    url: '/api/invoice-summary';
};

export type GetAllSummariesResponses = {
    /**
     * OK
     */
    200: Array<InvoiceSummaryDto>;
};

export type GetAllSummariesResponse = GetAllSummariesResponses[keyof GetAllSummariesResponses];

export type CreateInvoiceSummaryData = {
    body: InvoiceSummaryDto;
    path?: never;
    query?: never;
    url: '/api/invoice-summary';
};

export type CreateInvoiceSummaryResponses = {
    /**
     * Created
     */
    201: InvoiceSummaryDto;
};

export type CreateInvoiceSummaryResponse = CreateInvoiceSummaryResponses[keyof CreateInvoiceSummaryResponses];

export type GetAllGroupsData = {
    body?: never;
    path?: never;
    query: {
        groupFilter: GroupFilter;
    };
    url: '/api/group';
};

export type GetAllGroupsResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetAllGroupsResponse = GetAllGroupsResponses[keyof GetAllGroupsResponses];

export type CreateGroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/group';
};

export type CreateGroupResponses = {
    /**
     * Created
     */
    201: GroupDto;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type GetAllEnrollmentsData = {
    body?: never;
    path?: never;
    query: {
        enrollmentFilter: EnrollmentFilter;
    };
    url: '/api/enrollment';
};

export type GetAllEnrollmentsResponses = {
    /**
     * OK
     */
    200: Array<EnrollmentDto>;
};

export type GetAllEnrollmentsResponse = GetAllEnrollmentsResponses[keyof GetAllEnrollmentsResponses];

export type CreateEnrollmentData = {
    body: EnrollmentDto;
    path?: never;
    query?: never;
    url: '/api/enrollment';
};

export type CreateEnrollmentResponses = {
    /**
     * Created
     */
    201: EnrollmentDto;
};

export type CreateEnrollmentResponse = CreateEnrollmentResponses[keyof CreateEnrollmentResponses];

export type ShowAllCourtsData = {
    body?: never;
    path?: never;
    query: {
        courtFilter: CourtFilter;
    };
    url: '/api/court';
};

export type ShowAllCourtsResponses = {
    /**
     * OK
     */
    200: Array<CourtDto>;
};

export type ShowAllCourtsResponse = ShowAllCourtsResponses[keyof ShowAllCourtsResponses];

export type CreateCourtData = {
    body: CourtDto;
    path?: never;
    query?: never;
    url: '/api/court';
};

export type CreateCourtResponses = {
    /**
     * Created
     */
    201: CourtDto;
};

export type CreateCourtResponse = CreateCourtResponses[keyof CreateCourtResponses];

export type GetAllBlockingsData = {
    body?: never;
    path?: never;
    query: {
        courtBlockingFilter: CourtBlockingFilter;
    };
    url: '/api/court-block';
};

export type GetAllBlockingsResponses = {
    /**
     * OK
     */
    200: Array<CourtBlockingDto>;
};

export type GetAllBlockingsResponse = GetAllBlockingsResponses[keyof GetAllBlockingsResponses];

export type CreateBlockingData = {
    body: CourtBlockingDto;
    path?: never;
    query?: never;
    url: '/api/court-block';
};

export type CreateBlockingResponses = {
    /**
     * Created
     */
    201: CourtBlockingDto;
};

export type CreateBlockingResponse = CreateBlockingResponses[keyof CreateBlockingResponses];

export type UpdateInfoData = {
    body: CompanyInfoDto;
    path?: never;
    query?: never;
    url: '/api/company-info/update';
};

export type UpdateInfoResponses = {
    /**
     * OK
     */
    200: CompanyInfoDto;
};

export type UpdateInfoResponse = UpdateInfoResponses[keyof UpdateInfoResponses];

export type GetAllCoachesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/coach';
};

export type GetAllCoachesResponses = {
    /**
     * OK
     */
    200: Array<CoachDto>;
};

export type GetAllCoachesResponse = GetAllCoachesResponses[keyof GetAllCoachesResponses];

export type CreateCoachData = {
    body: CoachDto;
    path?: never;
    query?: never;
    url: '/api/coach';
};

export type CreateCoachResponses = {
    /**
     * OK
     */
    200: CoachDto;
};

export type CreateCoachResponse = CreateCoachResponses[keyof CreateCoachResponses];

export type GetAllBookingsData = {
    body?: never;
    path?: never;
    query: {
        bookingFilter: BookingFilter;
    };
    url: '/api/booking';
};

export type GetAllBookingsResponses = {
    /**
     * OK
     */
    200: Array<BookingDto>;
};

export type GetAllBookingsResponse = GetAllBookingsResponses[keyof GetAllBookingsResponses];

export type CreateBookingData = {
    body: BookingDto;
    path?: never;
    query?: never;
    url: '/api/booking';
};

export type CreateBookingResponses = {
    /**
     * Created
     */
    201: BookingDto;
};

export type CreateBookingResponse = CreateBookingResponses[keyof CreateBookingResponses];

export type GetAllAttendancesData = {
    body?: never;
    path?: never;
    query: {
        attendanceFilter: AttendanceFilter;
    };
    url: '/api/attendance';
};

export type GetAllAttendancesResponses = {
    /**
     * OK
     */
    200: Array<AttendanceDto>;
};

export type GetAllAttendancesResponse = GetAllAttendancesResponses[keyof GetAllAttendancesResponses];

export type CreateAttendanceData = {
    body: AttendanceDto;
    path?: never;
    query?: never;
    url: '/api/attendance';
};

export type CreateAttendanceResponses = {
    /**
     * Created
     */
    201: AttendanceDto;
};

export type CreateAttendanceResponse = CreateAttendanceResponses[keyof CreateAttendanceResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/{id}';
};

export type DeleteUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/user/{id}';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type ShowCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/current';
};

export type ShowCurrentUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type ShowCurrentUserResponse = ShowCurrentUserResponses[keyof ShowCurrentUserResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query: {
        userFilter: UserFilter;
    };
    url: '/user/all';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type GetAllAdminsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/all-admins';
};

export type GetAllAdminsResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetAllAdminsResponse = GetAllAdminsResponses[keyof GetAllAdminsResponses];

export type GetAllSlotsByGroupIdData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/training-slot/group/{groupId}';
};

export type GetAllSlotsByGroupIdResponses = {
    /**
     * OK
     */
    200: Array<TrainingSlotDto>;
};

export type GetAllSlotsByGroupIdResponse = GetAllSlotsByGroupIdResponses[keyof GetAllSlotsByGroupIdResponses];

export type GetSupportedConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules/supported-conditions';
};

export type GetSupportedConditionsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedConditionsResponse = GetSupportedConditionsResponses[keyof GetSupportedConditionsResponses];

export type GetSupportedConditionsPerSlotData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules/per-slot-cond';
};

export type GetSupportedConditionsPerSlotResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedConditionsPerSlotResponse = GetSupportedConditionsPerSlotResponses[keyof GetSupportedConditionsPerSlotResponses];

export type GetSupportedConditionsPerPackageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules/package-cond';
};

export type GetSupportedConditionsPerPackageResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedConditionsPerPackageResponse = GetSupportedConditionsPerPackageResponses[keyof GetSupportedConditionsPerPackageResponses];

export type ShowAllRulesWithMonthlyTypeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules/monthly-type-rules';
};

export type ShowAllRulesWithMonthlyTypeResponses = {
    /**
     * OK
     */
    200: Array<PricingRuleDto>;
};

export type ShowAllRulesWithMonthlyTypeResponse = ShowAllRulesWithMonthlyTypeResponses[keyof ShowAllRulesWithMonthlyTypeResponses];

export type GetSupportedConditionsPerMonthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pricing-rules/month-cond';
};

export type GetSupportedConditionsPerMonthResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedConditionsPerMonthResponse = GetSupportedConditionsPerMonthResponses[keyof GetSupportedConditionsPerMonthResponses];

export type GetPlayerByParentIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/player/user/{id}';
};

export type GetPlayerByParentIdResponses = {
    /**
     * OK
     */
    200: Array<PlayerDto>;
};

export type GetPlayerByParentIdResponse = GetPlayerByParentIdResponses[keyof GetPlayerByParentIdResponses];

export type ShowAllPackagesData = {
    body?: never;
    path?: never;
    query: {
        packageFilter: PackageFilter;
    };
    url: '/api/package/all';
};

export type ShowAllPackagesResponses = {
    /**
     * OK
     */
    200: Array<PackageDto>;
};

export type ShowAllPackagesResponse = ShowAllPackagesResponses[keyof ShowAllPackagesResponses];

export type GetAllSummariesByUserData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/invoice-summary/user/{userId}';
};

export type GetAllSummariesByUserResponses = {
    /**
     * OK
     */
    200: Array<InvoiceSummaryDto>;
};

export type GetAllSummariesByUserResponse = GetAllSummariesByUserResponses[keyof GetAllSummariesByUserResponses];

export type GetInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/company-info';
};

export type GetInfoResponses = {
    /**
     * OK
     */
    200: CompanyInfoDto;
};

export type GetInfoResponse = GetInfoResponses[keyof GetInfoResponses];

export type ShowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ShowResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type ShowResponse = ShowResponses[keyof ShowResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
